name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql postgresql-contrib
          sudo service postgresql start
          # Create database if it does not exist
          sudo -u postgres psql -c "DO \$\$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = 'ProductivityPal') THEN CREATE DATABASE ProductivityPal; END IF; END \$\$;"
          # Create user only if it does not exist
          sudo -u postgres psql -c "DO \$\$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'postgres') THEN CREATE USER postgres WITH PASSWORD 'test'; END IF; END \$\$;"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE ProductivityPal TO postgres;"

      - name: Build with Maven
        run: mvn clean install
        working-directory: backend

      - name: Run Tests
        run: mvn test
        working-directory: backend
